# Generated by Django 5.1 on 2024-09-01 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='last_name',
        ),
    ]
