# Generated by Django 5.1 on 2024-09-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_remove_tenant_email_remove_tenant_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='is_active',
        ),
    ]
