# Generated by Django 5.1 on 2024-09-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_alter_tenant_date_of_birth_alter_tenant_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
