# Generated by Django 5.1 on 2024-09-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaintReq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintrequest',
            name='response',
        ),
        migrations.AddField(
            model_name='complaintrequest',
            name='address',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='complaintrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='complaintrequest',
            name='user_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
