# Generated by Django 5.1 on 2024-09-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaintReq', '0002_remove_complaintrequest_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintrequest',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
