# Generated by Django 5.1 on 2024-08-31 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LeaseAgreement', '0001_initial'),
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseagreement',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_agreements', to='properties.property'),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_agreements', to='tenants.tenant'),
        ),
    ]
