# Generated by Django 5.1 on 2024-09-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaseAgreement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseagreement',
            name='last_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
